version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependabot-release"
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
      include: "scope"
